---
- hosts: launched
  connection: local
  tasks:

- name: Terminate aws instance
    local_action:
        module: ec2
        region: us-east-1
        state: 'absent'
        instance_ids: "{{ hostvars[groups['launched'][0]]['instance_id'] }}"
        wait: True
    tags:
         - terminateInstance

- name: Wait for the instances to be stopped by checking the ssh port
    wait_for: host="{{ hostvars[groups['launched']
