- hosts: localhost
  tasks:
    - name: get ec2 facts
      ec2_remote_facts:
        region: "us-east-1"
      register: ec2_facts
    - name: Debug
      debug:
         msg: "{{ item.id }}"
      with_items: "{{ec2_facts.instances}}"
#    - name: output
 #     command: pwd
  #    register: crnt
   # - name: "Save lsof log"
     # local_action:
      #    copy content="{{ ec2_facts }}" dest="{{ crnt.stdout }}/lsof.txt"
