- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: partition
      prompt: "Enter a user name"
      private: no
  tasks:
    - name: Ansible prompt example
      iam:
         iam_type: user
         name: "{{partition}}"
         state: present
